"""Add ScrapedContact model

Revision ID: 9ee8e62c1d7f
Revises: 52225cf828ee
Create Date: 2026-02-20 10:27:01.105656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee8e62c1d7f'
down_revision: Union[str, Sequence[str], None] = '52225cf828ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_contacts_email'), 'scraped_contacts', ['email'], unique=True)
    op.create_index(op.f('ix_scraped_contacts_id'), 'scraped_contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_contacts_id'), table_name='scraped_contacts')
    op.drop_index(op.f('ix_scraped_contacts_email'), table_name='scraped_contacts')
    op.drop_table('scraped_contacts')
    # ### end Alembic commands ###
