"""add_advanced_settings

Revision ID: b594ac3d8a0c
Revises: 9ee8e62c1d7f
Create Date: 2026-02-20 11:14:47.532915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b594ac3d8a0c'
down_revision: Union[str, Sequence[str], None] = '9ee8e62c1d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('target_roles', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('target_locations', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('daily_apply_limit', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('scrape_frequency_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'scrape_frequency_hours')
    op.drop_column('user_settings', 'daily_apply_limit')
    op.drop_column('user_settings', 'target_locations')
    op.drop_column('user_settings', 'target_roles')
    # ### end Alembic commands ###
