"""add_job_automation_columns

Revision ID: ccd3d3906fd4
Revises: 119dfdb43d9e
Create Date: 2026-02-25 16:22:07.585162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ccd3d3906fd4'
down_revision: Union[str, Sequence[str], None] = '119dfdb43d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Float(), nullable=True))
    op.add_column('user_settings', sa.Column('scrape_urls', sa.JSON(), nullable=True))
    op.add_column('user_settings', sa.Column('match_threshold', sa.Float(), nullable=True))
    op.add_column('user_settings', sa.Column('auto_apply_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('cold_mail_automation_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('daily_cold_mail_limit', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_refresh_token', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_access_token', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('use_gmail_for_send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'use_gmail_for_send')
    op.drop_column('user_settings', 'gmail_access_token')
    op.drop_column('user_settings', 'gmail_refresh_token')
    op.drop_column('user_settings', 'daily_cold_mail_limit')
    op.drop_column('user_settings', 'cold_mail_automation_enabled')
    op.drop_column('user_settings', 'auto_apply_enabled')
    op.drop_column('user_settings', 'match_threshold')
    op.drop_column('user_settings', 'scrape_urls')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
